#########
#
# workshop-template-b, evanwill
# a Jekyll template for a simple workshop website
# https://github.com/evanwill/workshop-template-b
#
#########

#######
# SITE SETTINGS
#
# title appears in the header
title: MissingKids24
# title-icon appears in the header to give some pizazz (leave blank for none)
# choose from Bootstrap Icons in _includes/bootstrap-icons
# find names on https://icons.getbootstrap.com/
# some options: code-slash file-code gear tools lightblub book bookmark-star
title-icon: 
# description, keywords, and image for meta tags
# these do not visibility appear on the pages, but used for SEO
description: "MissingKids24 create a comprehensive and compassionate online platform dedicated to addressing the heartbreaking issue of missing children. Our mission is to provide a centralized hub where families, law enforcement, and the community can collaborate to locate and bring missing children home."
keywords: "Missing Kid, UGAHacks, Uga hacks 2024, Challange"
# featured-image is added to metadata tags for social media sharing
# use a relative path to image in this repository or full URL
featured-image: "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxISEBUSEhIVEBUWFRUVDxUPEA8PDw8QFRUWFxUVFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMtNygtLisBCgoKBQUFDgUFDisZExkrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrKysrK//AABEIALcBEwMBIgACEQEDEQH/xAAbAAABBQEBAAAAAAAAAAAAAAADAAECBAUGB//EADwQAAIBAwIDBQUFBgYDAAAAAAABAgMEERIhBTFBIlFhcZEGE4GhsRQyQtHwI1JicuHxBxWCkrLBJKLC/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/APDhCHAYQ4sAMOkOOgGwIlgdICKQ+kkkSSAHoH0hlEXuwBaR9IVRH0AAcRLx2LKgJ0sgCURaAio45Dt45+vQCMIkKsCxGPVfIhX5/ACs0NpDKBLQBXcRtIdxGcQA4GwFcRnEAWBgrRHAEMCwSaFgBkPpFglECAzQWUSDQEBEhAMh0h0icYgQYkh5LcdIBsElEdImkBDAkFURSpbAR0k1ElT3X1JxiA0Yk1AlGISMQBe7FoLCiS92BXUSegnPEVl7GXc3blstl8wLVW4guufIq1LvPJeoCMWwkaS6gQjVaeVt5Bftb6pP5EcITigD07iL8Cwo5WxnSghU6ko8n+QGh7si4E7a4jLbk+78gzpgU3Ai4luUAbiBWcSDiWJRIOIAWhYCuIyiALA2AriRwA8d0RlES2C8wAYEEcBAQigsIjQQeEQKjW5OKFjcnFAJRJKJNImogDUR0E0CaAhTW/n9QukFN43LWMrIEIILEjCIeFJMCAzqJLcnOn+tzM4hU/CviBXurlzfh0QOnDJKnSyWYQ3+AAm8LANsnOO/kM4ADEwvuwkLdsCsIO6L/X68Sbobfrn+mBVx3GpZXOpYfP6lBUt/MlCDi8rmgNaUAUoFilPVFP8AWRpRApyiQcSzKJCSAruI2kM0RwAFxItBmiEkAFoaMsBGgckAUQEYCxBFqnADTRaprZsChjcIkNFBYIBRQSKEkTQCcSLiGQ0ogVKkNgllLMcd2xNxIUo4l5/VAHS/XxC02Dl0/XP+wylh4APWeEYUVqll95rVpbPyKFnACxRobbL6ci1ZcOcm21z+SwXOH0M8/A6m04d2U0sZ8OSA4qpwt62nnd/LGRp2DSW3N4+j+p2VxZpvl5fDYo1qCWFjr/Rgc7bcOlOXI1ocGxP0x64/I6XhFmnyWOqfzLdezkpLGOfP4gcVdcFxN92n13x/38jP+y80+a/t9T0GraqW8lzT7uT/AKmNccN7Ta57Z83kDmJcOTzhcuXl1+pB2vZx38m+j/SOgnQ228U2ujKlWGV5Za8lyAweGyxqi+j9C2VYxxVfjktsAUog3EOyDQAMEZINIFUWwEGiLRPJFgCkgckGkCkgBiHwIC5SRYqfcYGkFuH2PNgVooLFAoh4ATiiSQokgGwESIpE0gBTiBmvluWmirVAPFA7jZitZZj+ugS4WUBXnLZhLahgrGzZxWUBucCsNWM/0XI6yFNY+hR4ZRxFY67s0d9lFan07gAVLJ+HxffzBvgOprdPO0UnnC6mnHg9WpvOenuSWdvPIy4Xc0XqhUjNdzi1JL4PAFuw4XoWMb4x8ixLh2fn8yNte1X96mvFpv6GxReYpgYFxwxyfLCxjbmsb/kc9ecPactnhz2+H9n6noNaWmOTFuuJUYp6k2/5GwOOjw145Y3f1f5lWpwxb5Nq941CcsRi0v4ouOfLICu1JbdwHnNxD9vjuCyRc4jQ01Zd/Lz6r5FOQDYISCEGAOUQVTkHkwNRbAVYyCMDTkgkd+QDSBSLcaHf6IaqkgKTQgzaEAakx7qXJeYOkyNaeZeQEoh4FeIeAFiBPAOAVAJIdIdISQCaAVoZLDAVWBWs5btZ67GpwyyderGmnjL3f7sUst+iMO12fxZ23sDSUqtVvnGmseUpbv5Aak/YyjOk9MHTltolqcpP+ZcjnY8Lq0K9OFRc879Hj9I9Nq3EKVBuba1LPZWZJdMGJxipGsqVTDzF9Vh7rqvgBdsaexq21LG7KfDI7I0atJtYXUCpdcehBSlnKprNRxjKcYfzS2jF78m8shwz2soVnpjJqSWXGdOdN4zjO+3PxLM6LdtO3cfdp4cJwhFxUovK1RWHjPVblP2X4c4TdS6rKqoxqQp04++qrFR9rLmtlthJAdBbaZLYsxi0jL4fQlDvSUuypc9D5L4cjac0lzAqVZ95Rl7rVulJ9yWoDfV3PW4co7Yzu2cl7Y0YU5UtXvLim121QquEfeZ7WpRy1tjG3fkDsLq4pSWlr/dBpfNGBxGzUWnFad+nJpg7Kxox4enKXuquqX2aa0q5lRz2FUgkte2fvJbY5BY1HKktW7XPbGfgBwvHKb9/NLfGG8LOOyjJZ6FOx7DkspzlqzHm1FpJeRwV5j3s8bLVLHll4ADki2O2RyBHIObJyYGowKlCOZtPv3L9aaisR2J/5NJW32tTTTeNOHqTU3Hn8PmVEssCcZ7A6swjiCnEAORCaHAlCQNS3It7Mr5AvwkGhIy1J95oUEgLUJBoyJ28Y9yNGhGPcvRAUYsdG3RhHuXoiy7SEucV8Fj6Ac6yvW5GvfcM07xeF3S3XqYXElKEcNYb2XigKVI6f2IvlTvIqTwqkXTfdl4cfmkvicvBBoya3Tw1un3NcmB7VxChn3cmnKKwppLLjjwAcRnCUZSh0mljbKx3g/Zri/2mjGpnfaNSK3xUXPP1+IXiNKKbklhycVLpnTnG3qBc4bT7K8TetqHUwIVtOFzeOSTbLVnxOUm1lRa5RnqU5eSSA6GMVjcBVhFPOlehmSvqia1Rcc7J8033eY3+a5elNeb5L+vgBYvqyjHVNqEc839F3sz1xCVVPQkl01Zcmu977AuI0JVpQWW8NyedsLksR+PyNCyjGnHGPNgZFCFWnNyxz5rfD+I9WpOX4Uu/tTkjZqVqfX5kYuLScXs+oGLGqtvewS/iisNeLXUhe08LKw0+WOTRqcTt4yXTPetv7nM3alTTjvju5rHevHwAuxqfsot7af8Aill/Q8vuJZk33tv1Z6Ve206tu4UUlmDipSm5JqWMvGNspHH3HspdRhrUFNfwy7Xo8AYDIthK1KcW4uMk4/eTi8x810KspgPUmV5Zk8IfdvCL9G30rx6gQi5+7jTcm4xbcY9FKW7fiQcQ8kBqMAE2CnINMr1GBBscG2ICCZF02MmEjIAeh9z9C1RkKnMab7QGlQqGhRqmLRmXaNQDcoVTRt6hhW8jUt5gakoqSOb9oODyliUO1j8PJ4fd+R0FJPAV0WwPN3TcXhpp+KwyR3d3w9SWJRT80Yd5wJfhzH5oCl7P8dqWlRyh2oyxrg28Sxya7n4nVcM9oq99dQjClppxy6rznGYyUenf9DibmynDms+KPU/8JrTRba9O85Sk34J6V8ooDpoUo0YapdqctorrJ9y7kWOF2ay6k95PeT6Jdy8Cgq0ql3U6xp4hHHSTWZf/ACalxUc2qa2X48c2v3QKN/GV09MOzTi8JrnN968PEsfafcUJwqqLjhpPGJyk+S25tvr8S3xG7pWlvKpNqEYx9PI83ocflWqOdXdSfYSeVTi/w+fe+vyA27S/qwhhUYZ5twn2pPxcluDjxu7lPH2bEVzc6lNprq+y2/kXbapCUc6XjONWl6M9FnlknPT0A5nidW6rSlCM1Ti+bdKWIrPaxLvxsdNw+g4wj23JKOIpKKfnh82C9zLo9PmydWhhZTy+u2ACwS59pvrrbf15FPiFNSW/yD0aj077/EFXhlYAreyNROdSg2+y9l10yzj5pr4G/c2ihmK+687Pp5GZ7KWyVxUltnEM+H3zf4pNJrPfj1A57Tok5OOU9qnfjpLxOJ9tfZnTP39FLRPeajjEX+8vM728i1LK5PmvDoZly5KOhrMJZS/hz0A86tbJRXiFnTwdJw/humu9W6SWhPfbvMvjkY++lhY8u/AGHUwVajLlaJRqsAM5FebJzkAmwGYxFsQEEySZAdAFjInNgUyeQD05F2hIzISLtvMDatWbNmkc9bVTZs6wHRW1JGlTt0Y1pW5GvRqbARr2yM25tzakynXjkDmrqknzPRfZGl7u1h4QXrzZx1a0U5qK68/BdTsraThR0rbKx44wgJ+z1Pac3znOUvhnC+SRe4WnrlL95t/kQh+zotr93bzLfCoYpryA4P8AxC4u5XUKGdUIx1VI9JTk0o7dXz9SzwD2JhPFWcHBP7tNtqKz1lH/AK9QXs5wx1eIXN3Wjle90UFJZxpW8l8NK/3HY8c43StKEpyfhFcnOXRL8+gGZ7R8QdtauhFe9csKEYqKkoppuTfcunXJzlhxVT7OJRl1jUjJej5Mja8TVZucpZlLdvpnuXgjQhR1bPHQA1nWTlhx9S5c1Irkvh0Awtdsv1Kt1X0vlnzYB4ppNvZLmCVd7tJvos7LzK1a6lLCwoxXT95+IKvxCMYvLjH/AFJgbvsjDs1Kj5zm1/ph2fqpepo8ShqXlv6GP7KXH/jR8cyXlKTkvqXrq5ArVORS4rVWjSvAhcXW/Myb68AnVulqj4Z9MP8AoctxWt2211LNe8xl+D/6OeuLrO/eA1eoUasxVqxWnMBpyBMk0RbAWBDCAEOMICSZLIMkgJRZYpSKyZOEgNS3qGnbVzBpVC7QrgdVZ3Jt2t0cXb3JqW14B2NKvknLDRz9C+LkL1AXIUu3nwl9GakK+YZ8mYf2tYk88ov1ZYsrtaQOo98ppLoaXvlGm0u7Y5ahcYXPkXleJ4yBocKpqKS6L9NnKe1nFoTunSazGCw/CpJZ+mk6qncpI849o5Up3dXPZllLMW09oRQE6thTfapPQ+qXJ+ceoa0vqtPGtZXxcWvB/mZeZwWYy1r/ANl6FmHEcrPNfii9mmB1FLjUXDl6PJjX3FMvKX9ihWrUmtSyvDkZFa5y8LZAblS/bSTwl55bMfi9+lHGVuV6txFLnkxb27T5LPl+YHqPAbnTQpruhH/igtzeHOcNvf2cf5Y/RD17wC1dXRj3l0Curoyrm4AhxC5eHjm9jGqzl1+RYq1csrzkAGUycJbEJEUwJykDbE2RAfIiORAMIQgEIQgHJIgSTAJCQeFQqodMDTp1y3SujFjMNGoB0NG98S5C+8TmIVQsblgdI73x6GhaXuxx0bo0KF0B2VG+LlK+Rx1O98SxC/8AEDs/8y2PP+JrVWqSzznJ/Nl+fEsLmYUrnLyAWNzOPVk/tjzlZXeVJXBB1gNCpdprYq1Kjfd9Sq6pH34FmS79yvVhHyIuuBnVA3LO5xCO/RL0J1bowaVzjYJK4AuV7goVqoOpVATmBKUgUpEZTItgJsYQwDtkRCAQhCAQhCAQhCAQhCAdEsiEA8WTTGEBJTJKoIQE1ULFOsOIA0bgIrliEBCtdPBU96IQDOqR96IQDOqR94IQEXUIuQhAR1E9YhARlMG2OICIwhAJjCEAhCEAhCEB/9k="
# add search box to footer? true/false
search: true

# author settings for cc-by, appears in the footer and credits
author: 
# your github username for link [optional]
github_username: NikhitaKunthu52
# year or date published
pub_year: 2024
# location of code, the full url to your github repository
source-code: https://github.com/Nikhitakunthu52/UGAHacks24

##########
# URL VARIABLES [optional!!]
#
# Optional if using GitHub Pages! If building manually, these must be set correctly.
# When using github pages just leave these blank!
#
# use url for the domain, e.g. https://evanwill.github.io
# on gh-pages follow the pattern: https://username.github.io
url:
# use baseurl to add subsection of the domain, e.g. /workshop-template-b
# on gh-pages this is a / followed by the name of the repository
# baseurl is your github repository's name prefixed with a /
baseurl:


##########
# GOOGLE ANALYTICS [optional!]
#
# leave this blank or comment out to NOT include google code
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
google-analytics-id:

##########
# ROBOTS EXCLUDE [optional!]
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 


#######
# BUILD SETTINGS [usually leave as is]
#
# Defaults to simplify front matter
defaults:
  - scope:
      path: "content"
    values:
      layout: "section"
# ignore stuff
exclude: [README.md, LICENSE, assets/lib/README.md]
# Build settings
markdown: kramdown
